var json_Pointdedpart_10 = {
"type": "FeatureCollection",
"name": "Pointdedpart_10",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
"features": [
{ "type": "Feature", "properties": { "id": null, "Depart": null, "Pt-Depart": null, "point": null, "layer": "Depart", "path": "D:\\GEOMATIQUE\\Projets\\Cartes Randonn�es\\001 - Cartes Saussignac - Monestier - Gageac Rouillac - Razac Saussignac\\Web-mapping\\Elements-cartes\\Point-depart\\Gageac-Rouillac\\Depart.shp" }, "geometry": { "type": "Point", "coordinates": [ 0.348424383767842, 44.798551997427715 ] } },
{ "type": "Feature", "properties": { "id": null, "Depart": null, "Pt-Depart": null, "point": null, "layer": "Point-Depart", "path": "D:\\GEOMATIQUE\\Projets\\Cartes Randonn�es\\001 - Cartes Saussignac - Monestier - Gageac Rouillac - Razac Saussignac\\Web-mapping\\Elements-cartes\\Point-depart\\Monestier\\Point-Depart.shp" }, "geometry": { "type": "Point", "coordinates": [ 0.326628910294656, 44.773390153409871 ] } },
{ "type": "Feature", "properties": { "id": null, "Depart": null, "Pt-Depart": null, "point": null, "layer": "Point-Depart", "path": "D:\\GEOMATIQUE\\Projets\\Cartes Randonn�es\\001 - Cartes Saussignac - Monestier - Gageac Rouillac - Razac Saussignac\\Web-mapping\\Elements-cartes\\Point-depart\\Coutures\\Point-Depart.shp" }, "geometry": { "type": "Point", "coordinates": [ 0.297497043591792, 44.766684609504608 ] } },
{ "type": "Feature", "properties": { "id": null, "Depart": null, "Pt-Depart": null, "point": null, "layer": "Point-Depart", "path": "D:\\GEOMATIQUE\\Projets\\Cartes Randonn�es\\001 - Cartes Saussignac - Monestier - Gageac Rouillac - Razac Saussignac\\Web-mapping\\Elements-cartes\\Point-depart\\La-Bastide\\Point-Depart.shp" }, "geometry": { "type": "Point", "coordinates": [ 0.34279790411747, 44.774265242484127 ] } },
{ "type": "Feature", "properties": { "id": null, "Depart": null, "Pt-Depart": null, "point": null, "layer": "Point-de-Depart", "path": "D:\\GEOMATIQUE\\Projets\\Cartes Randonn�es\\001 - Cartes Saussignac - Monestier - Gageac Rouillac - Razac Saussignac\\Web-mapping\\Elements-cartes\\Point-depart\\Razac-1\\Point-de-Depart.shp" }, "geometry": { "type": "Point", "coordinates": [ 0.285268473393167, 44.803686182827128 ] } },
{ "type": "Feature", "properties": { "id": null, "Depart": null, "Pt-Depart": null, "point": null, "layer": "point-depart", "path": "D:\\GEOMATIQUE\\Projets\\Cartes Randonn�es\\001 - Cartes Saussignac - Monestier - Gageac Rouillac - Razac Saussignac\\Web-mapping\\Elements-cartes\\Point-depart\\Sausignac\\point-depart.shp" }, "geometry": { "type": "Point", "coordinates": [ 0.326399975952001, 44.799947825229268 ] } }
]
}
