var json_Pointdarrive_9 = {
"type": "FeatureCollection",
"name": "Pointdarrive_9",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
"features": [
{ "type": "Feature", "properties": { "id": null, "Arrivee": null, "Pt-arrivee": null, "point": null, "layer": "Arrivee", "path": "D:\\GEOMATIQUE\\Projets\\Cartes Randonn�es\\001 - Cartes Saussignac - Monestier - Gageac Rouillac - Razac Saussignac\\Web-mapping\\Elements-cartes\\Point-arrivee\\Gageac-Rouillac\\Arrivee.shp" }, "geometry": { "type": "Point", "coordinates": [ 0.348214377259529, 44.798357200615499 ] } },
{ "type": "Feature", "properties": { "id": null, "Arrivee": null, "Pt-arrivee": null, "point": null, "layer": "Point-Arrivee", "path": "D:\\GEOMATIQUE\\Projets\\Cartes Randonn�es\\001 - Cartes Saussignac - Monestier - Gageac Rouillac - Razac Saussignac\\Web-mapping\\Elements-cartes\\Point-arrivee\\Razac-3\\Point-Arrivee.shp" }, "geometry": { "type": "Point", "coordinates": [ 0.285368277094983, 44.803681937246736 ] } },
{ "type": "Feature", "properties": { "id": null, "Arrivee": null, "Pt-arrivee": null, "point": null, "layer": "Point-Arrivee", "path": "D:\\GEOMATIQUE\\Projets\\Cartes Randonn�es\\001 - Cartes Saussignac - Monestier - Gageac Rouillac - Razac Saussignac\\Web-mapping\\Elements-cartes\\Point-arrivee\\Coutures\\Point-Arrivee.shp" }, "geometry": { "type": "Point", "coordinates": [ 0.297492254177855, 44.766597078481354 ] } },
{ "type": "Feature", "properties": { "id": null, "Arrivee": null, "Pt-arrivee": null, "point": null, "layer": "Point-Arrivee", "path": "D:\\GEOMATIQUE\\Projets\\Cartes Randonn�es\\001 - Cartes Saussignac - Monestier - Gageac Rouillac - Razac Saussignac\\Web-mapping\\Elements-cartes\\Point-arrivee\\Monestier\\Point-Arrivee.shp" }, "geometry": { "type": "Point", "coordinates": [ 0.326855232514949, 44.773355675585854 ] } },
{ "type": "Feature", "properties": { "id": null, "Arrivee": null, "Pt-arrivee": null, "point": null, "layer": "Point-Arrivee", "path": "D:\\GEOMATIQUE\\Projets\\Cartes Randonn�es\\001 - Cartes Saussignac - Monestier - Gageac Rouillac - Razac Saussignac\\Web-mapping\\Elements-cartes\\Point-arrivee\\La-Bastide\\Point-Arrivee.shp" }, "geometry": { "type": "Point", "coordinates": [ 0.342891456849534, 44.774107109685083 ] } },
{ "type": "Feature", "properties": { "id": null, "Arrivee": null, "Pt-arrivee": null, "point": null, "layer": "Point-d-arrivee", "path": "D:\\GEOMATIQUE\\Projets\\Cartes Randonn�es\\001 - Cartes Saussignac - Monestier - Gageac Rouillac - Razac Saussignac\\Web-mapping\\Elements-cartes\\Point-arrivee\\Razac-2\\Point-d-arrivee.shp" }, "geometry": { "type": "Point", "coordinates": [ 0.285654840627852, 44.803474196184311 ] } },
{ "type": "Feature", "properties": { "id": null, "Arrivee": null, "Pt-arrivee": null, "point": null, "layer": "point-arrivee", "path": "D:\\GEOMATIQUE\\Projets\\Cartes Randonn�es\\001 - Cartes Saussignac - Monestier - Gageac Rouillac - Razac Saussignac\\Web-mapping\\Elements-cartes\\Point-arrivee\\Sausignac\\point-arrivee.shp" }, "geometry": { "type": "Point", "coordinates": [ 0.32590174081895, 44.800578152636582 ] } }
]
}
